@startuml setGeneralBudgetAD
|Front-End|
start
:המשתמש בוחר "הגדרת תקציב כללי";
:מזין סכום וטווח תאריכים;
->|Server|

|Server|
:קבלת בקשה להגדרת תקציב כללי;
:בדיקת הרשאות;
:בדיקת תקינות קלט (סכום חיובי, תאריכים תקינים);
if (קלט לא תקין?) then (כן)
    :שליחת 400 Bad Request;
    ->|Front-End|
    :הצגת הודעת שגיאה;
    stop
endif
:בדיקה אם קיים תקציב כללי בטווח תאריכים חופף;
-->|MongoDB|
|MongoDB|
:שאילתה לבדיקת תקציבים קיימים;
-->|Server|
|Server|
if (קיים תקציב חופף?) then (כן)
    :שליחת 400 Bad Request;
    ->|Front-End|
    :הצגת הודעה "כבר קיים תקציב בטווח זה";
    stop
endif
:שמירת תקציב כללי חדש;
-->|MongoDB|
|MongoDB|
:הכנסת מסמך תקציב;
-->|Server|
|Server|
:שליחת 201 Created;
->|Front-End|
|Front-End|
:הצגת הודעת "תקציב הוגדר בהצלחה";
stop
@enduml