@uri = http://localhost:5500/api/

### Register a new user
POST {{uri}}user/register
Content-Type: application/json

{
    "username": "user",
    "password": "1234",
    "createdAt": "2023-10-01T12:00:00Z",
    "updatedAt": "2023-10-01T12:00:00Z"
}

### get user by id
POST {{uri}}user/get-user-by-id
Content-Type: application/json

{
    "id": "682d8900ecddb08b392789a5"
}

###validate user
POST {{uri}}user/validate
Content-Type: application/json

{
    "username": "user",
    "password": "1234"
}
